openapi: 3.0.3
info:
  title: FDA.gov v2 - Data Ingestion API
  description: |-
    API for submitting health data to the FDA.gov v2 Platform. 
    This includes structured observations (time-series data) and raw files.
    All endpoints require OAuth 2.0 authentication.
  version: 1.0.0
servers:
  - url: https://api.fda-v2.gov/
tags:
  - name: Ingestion
    description: Endpoints for submitting data.
paths:
  /v1/ingest/observations:
    post:
      tags:
        - Ingestion
      summary: Submit a batch of observations
      description: |-
        Submits a batch of structured time-series observations.
        The data is processed asynchronously. The response will include a `job_id` 
        which can be used to track the status of the ingestion job.
      security:
        - oAuth2AuthCode: [data:write]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObservationBatch'
      responses:
        '202':
          description: Accepted. The batch has been queued for processing.
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: string
                    format: uuid
                    description: The ID for the asynchronous processing job.
        '400':
          description: Bad Request. The request body is malformed or invalid.
        '401':
          description: Unauthorized. Invalid or missing authentication token.

  /v1/ingest/files:
    post:
      tags:
        - Ingestion
      summary: Upload a raw file
      description: |-
        Uploads a raw file (e.g., CSV, PDF, genomic data) for asynchronous processing.
        The file will be mapped and validated by a corresponding plugin.
      security:
        - oAuth2AuthCode: [data:write]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The file to upload.
                source_id:
                  type: string
                  format: uuid
                  description: The ID of the data source this file belongs to.
      responses:
        '202':
          description: Accepted. The file has been queued for processing.
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: string
                    format: uuid
                    description: The ID for the asynchronous processing job.
        '400':
          description: Bad Request. Missing file or invalid form data.
        '401':
          description: Unauthorized. Invalid or missing authentication token.

  /v1/ingest/jobs/{job_id}:
    get:
      tags:
        - Ingestion
      summary: Get ingestion job status
      description: Retrieves the current status and outcome of an asynchronous ingestion job.
      security:
        - oAuth2AuthCode: [data:read]
      parameters:
        - in: path
          name: job_id
          schema:
            type: string
            format: uuid
          required: true
          description: The ID of the ingestion job.
      responses:
        '200':
          description: OK. Returns the job status.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionJob'
        '404':
          description: Not Found. The specified job_id does not exist.
        '401':
          description: Unauthorized. Invalid or missing authentication token.

components:
  schemas:
    Observation:
      type: object
      required:
        - timestamp
        - variable_name
        - value
        - unit
      properties:
        timestamp:
          type: string
          format: date-time
          description: The ISO 8601 timestamp for the observation.
        variable_name:
          type: string
          description: A standardized name for the variable (e.g., "blood_glucose"). Will be mapped to a variable_id.
        value:
          type: number
          format: float
        unit:
          type: string
          description: The UCUM code for the unit (e.g., "mg/dL").
    
    ObservationBatch:
      type: object
      properties:
        source_id:
          type: string
          format: uuid
          description: The ID of the data source for this batch.
        observations:
          type: array
          items:
            $ref: '#/components/schemas/Observation'

    IngestionJob:
      type: object
      properties:
        job_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [queued, processing, completed, failed]
        created_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
        errors:
          type: array
          items:
            type: object
            properties:
              error_code:
                type: string
              message:
                type: string
              row_index:
                type: integer

  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.fda-v2.gov/oauth2/auth
          tokenUrl: https://auth.fda-v2.gov/oauth2/token
          scopes:
            data:write: Grants write access to data.
            data:read: Grants read access to data. 